export enum TripPlannerEvents {
  Load = 'TripPlannerEvents-Load',
  ProbillAssign = 'TripPlannerEvents-ProbillAssign',
  ProbillUnassign = 'TripPlannerEvents-ProbillUnassign',
  ProbillAssignFromEventDialog = 'TripPlannerEvents-ProbillAssign-FromEventDialog',
  ProbillUnassignFromEventDialog = 'TripPlannerEvents-ProbillUnassign-FromEventDialog',
  ProbillAssigned = 'TripPlannerEvents-ProbillAssigned',
  TruckAssign = 'TripPlannerEvents-TruckAssig',
  TruckUnassign = 'TripPlannerEvents-TruckUnassign',
  TruckAssignFromEventDialog = 'TripPlannerEvents-TruckAssign-FromEventDialog',
  TruckUnassignFromEventDialog = 'TripPlannerEvents-TruckUnassign-FromEventDialog',
  TrailerAssign = 'TripPlannerEvents-TrailerAssign',
  TrailerUnassign = 'TripPlannerEvents-TrailerUnassign',
  TrailerAssignFromEventDialog = 'TripPlannerEvents-TrailerAssign-FromEventDialog',
  TrailerUnassignFromEventDialog = 'TripPlannerEvents-TrailerUnassign-FromEventDialog',
  Pickup = 'TripPlannerEvents-Pickup',
  Unload = 'TripPlannerEvents-Unload',
  Deliver = 'TripPlannerEvents-Deliver',
  Acquire = 'TripPlannerEvents-Acquire',
  Border = 'TripPlannerEvents-Border',
  Drop = 'TripPlannerEvents-Drop',
  Release = 'TripPlannerEvents-Release',
  Hook = 'TripPlannerEvents-Hook',
  HookDrop = 'TripPlannerEvents-HookDrop',
  DropHook = 'TripPlannerEvents-DropHook'
}
